BulkFetcherの機能をマージ
taka0125/google_spreadsheet_fetcher pull request #5
Opened 2020-07-16 02:37 UTC by enzirion

https://github.com/enzirion/google_spreadsheet_bulk_fetcher
↑のgemの機能をこちらのgemに取り込めるよう修正しました。
具体的な修正内容は以下の2店です

- `SheetsService` 取得処理の切り出し
- 一括取得の機能を `BulkFetcher` としてこちらのgemに取り込み

こちら確認していただけますと幸いです 🙇

2020-07-16 10:30 UTC, taka0125 requested changes
@enzirion みました。ご確認下さい。

あと大事な事を忘れています。

https://github.com/taka0125/google_spreadsheet_fetcher/blob/master/google_spreadsheet_fetcher.gemspec#L9-L10

へ追記をどうぞ。

2020-07-16 10:30 UTC, taka0125 commented on README.md
> +GoogleSpreadsheetBulkFetcher.configure do |config|
```suggestion
GoogleSpreadsheetFetcher.configure do |config|
```

2020-07-16 10:30 UTC, taka0125 commented on lib/google_spreadsheet_fetcher/sheets_service_builder.rb
> +
不要な空行があります

2020-07-16 10:30 UTC, taka0125 commented on README.md
>  fetcher = GoogleSpreadsheetFetcher::Fetcher.new(credential_store_file, user_id, sheet_key)
元々のサンプルが間違っていそうですね。

```ruby
fetcher = GoogleSpreadsheetFetcher::Fetcher.new(sheet_key, user_id)
```

2020-07-17 01:33 UTC, enzirion commented
ご確認ありがとうございます！指摘いただいた点修正し、gemのバージョンアップ行わせていただきます!

2020-07-17 01:42 UTC, enzirion commented
# 修正点

2020-07-17 01:44 UTC, enzirion commented
# 修正点
- READMEの間違っていた箇所を修正
- 不要な改行が含まれていたので削除
- gemspecに自分の情報追加

再度ご確認いただけますと幸いです！

2020-07-17 01:48 UTC, taka0125 approved these changes
@enzirion 👍

2020-07-17 02:03 UTC, merged